// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_skaAJA7QlT7jV5sM3wgWd0WfrrlQpY',
    appId: '1:213476817441:web:5f6d4996c94653d9958160',
    messagingSenderId: '213476817441',
    projectId: 'cedar-setup-470114-r7',
    authDomain: 'cedar-setup-470114-r7.firebaseapp.com',
    storageBucket: 'cedar-setup-470114-r7.firebasestorage.app',
    measurementId: 'G-8QD3VZ3S7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hYHm6JE4r_g3yDnb2IQmRd0t82qa7EU',
    appId: '1:213476817441:android:d4f231823d85d255958160',
    messagingSenderId: '213476817441',
    projectId: 'cedar-setup-470114-r7',
    storageBucket: 'cedar-setup-470114-r7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDQDNduEDurdS5AFBlDuI5-mZSc4uJT0',
    appId: '1:213476817441:ios:b8627f22184781bb958160',
    messagingSenderId: '213476817441',
    projectId: 'cedar-setup-470114-r7',
    storageBucket: 'cedar-setup-470114-r7.firebasestorage.app',
    iosBundleId: 'com.kktc.ilankktc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCDQDNduEDurdS5AFBlDuI5-mZSc4uJT0',
    appId: '1:213476817441:ios:3b710982f71346a5958160',
    messagingSenderId: '213476817441',
    projectId: 'cedar-setup-470114-r7',
    storageBucket: 'cedar-setup-470114-r7.firebasestorage.app',
    iosBundleId: 'com.example.kktcaraba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_skaAJA7QlT7jV5sM3wgWd0WfrrlQpY',
    appId: '1:213476817441:web:9770eea79d5a773b958160',
    messagingSenderId: '213476817441',
    projectId: 'cedar-setup-470114-r7',
    authDomain: 'cedar-setup-470114-r7.firebaseapp.com',
    storageBucket: 'cedar-setup-470114-r7.firebasestorage.app',
    measurementId: 'G-5Q307Z1NC3',
  );
}